import AppKit

/// Watches the general pasteboard and feeds new entries into `ClipboardStore`.
///
/// macOS has no pasteboard-change notification, so we poll `changeCount` on a
/// timer (only while enabled). Entries marked concealed/transient by the source
/// (password managers set `org.nspasteboard.ConcealedType` /
/// `org.nspasteboard.TransientType`) are never stored — privacy first.
@MainActor
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    private let pollInterval: TimeInterval = 0.6

    private(set) var isRunning = false

    // Source-set markers we must not capture.
    private static let concealedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    // Tiered payload thresholds. Files are referenced by path (never read), so
    // they have no size limit.
    //
    // SOFT guard — above it we keep the clip but store it UNENCRYPTED, skipping
    // the in-memory ciphertext copy that sealing a big blob needs. It still
    // restores (paste-back works) and keeps OS file protection; only app-level
    // encryption is dropped, which is the cost of holding large clips cheaply.
    //
    // HARD guard — above it we keep metadata only (no bytes), so a pathological
    // clip (e.g. a 1 GB paste) can't spike memory or stall the UI.
    private static let softTextBytes = 1 * 1024 * 1024         // ≤1 MB text → encrypt
    private static let maxTextBytes = 100 * 1024 * 1024        // >100 MB text → metadata only
    private static let softImageBytes = 8 * 1024 * 1024        // ≤8 MB PNG → encrypt
    private static let maxImagePixels = 50_000_000             // >50 MP → metadata only (no decode)

    func start() {
        guard !isRunning else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer.scheduledTimer(withTimeInterval: pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // Capture latency is not precision-sensitive; tolerance lets macOS
        // coalesce the wakeup with other timers and cuts idle power.
        timer.tolerance = pollInterval / 2
        self.timer = timer
        RunLoop.main.add(timer, forMode: .common)
        isRunning = true
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isRunning = false
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        capture(pb)
    }

    private func capture(_ pb: NSPasteboard) {
        // Respect concealed/transient markers (passwords, OTP, etc.).
        if let types = pb.types, !Self.concealedTypes.isDisjoint(with: Set(types)) {
            return
        }

        // 1. Files (one or many) — reference by path, don't copy bytes.
        if let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            for url in urls { ClipboardStore.shared.addFile(url) }
            return
        }

        // 2. Image.
        if let images = pb.readObjects(forClasses: [NSImage.self], options: nil) as? [NSImage],
           let image = images.first {
            let (w, h) = Self.pixelSize(of: image)
            // HARD guard on pixel count BEFORE decoding: a giant image's TIFF/PNG
            // would allocate hundreds of MB. Over the limit → metadata only.
            if w > 0, h > 0, w * h > Self.maxImagePixels {
                ClipboardStore.shared.addOversizeImage(width: w, height: h)
                return
            }
            if let png = Self.pngData(from: image) {
                // Keep + restore at any decoded size; encrypt only the small ones.
                ClipboardStore.shared.addImage(image, pngData: png,
                                               encrypt: png.count <= Self.softImageBytes)
                return
            }
        }

        // 3. Text.
        if let string = pb.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let bytes = string.utf8.count
            if bytes > Self.maxTextBytes {
                // HARD guard → metadata-only marker, never persist the payload.
                ClipboardStore.shared.addOversizeText(byteCount: bytes,
                                                      preview: String(string.prefix(140)))
            } else {
                // Keep + restore; encrypt only below the soft threshold.
                ClipboardStore.shared.addText(string, encrypt: bytes <= Self.softTextBytes)
            }
        }
    }

    /// Largest pixel dimensions across the image's representations (falls back to
    /// the point size if no bitmap rep reports pixels). Cheap — reads rep
    /// metadata without decoding pixel data.
    private static func pixelSize(of image: NSImage) -> (Int, Int) {
        var w = 0, h = 0
        for rep in image.representations {
            w = max(w, rep.pixelsWide)
            h = max(h, rep.pixelsHigh)
        }
        if w == 0 || h == 0 { return (Int(image.size.width), Int(image.size.height)) }
        return (w, h)
    }

    private static func pngData(from image: NSImage) -> Data? {
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
