import AppKit

/// Watches the general pasteboard and feeds new entries into `ClipboardStore`.
///
/// macOS has no pasteboard-change notification, so we poll `changeCount` on a
/// timer (only while enabled). Entries marked concealed/transient by the source
/// (password managers set `org.nspasteboard.ConcealedType` /
/// `org.nspasteboard.TransientType`) are never stored — privacy first.
@MainActor
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private var timer: Timer?
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    private let pollInterval: TimeInterval = 0.6

    private(set) var isRunning = false

    /// Whether a captured item is written to the history store. False when the
    /// monitor runs ONLY to feed the `clipboard.changed` extension event (history
    /// off, but an extension subscribes) — then a poll makes zero `ClipboardStore`
    /// writes and nothing is persisted.
    var captureHistory = true

    /// Live gate consulted before the `clipboard.changed` payload is built, so a
    /// copy costs nothing extra when no enabled extension subscribes.
    /// nil = always emit (tests / unset), matching `SystemEventWatchers`.
    var shouldEmitChange: (() -> Bool)?

    /// Emits the `clipboard.changed` payload JSON for the registry to broadcast.
    /// Set by `AppDelegate`; nil in headless runs.
    var emitChange: ((String) -> Void)?

    /// Set by `suppressNextChange()`, consumed by the next poll that sees a delta.
    private var suppressNext = false

    /// Byte cap on the payload's `text` field: a 40 MB paste must not be marshalled
    /// across the JSON boundary into Lua. Handlers needing the whole clip call
    /// `host.clipboard.read()`.
    private static let maxEventTextBytes = 8 * 1024

    // Source-set markers we must not capture.
    private static let concealedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    // Tiered payload thresholds. Files are referenced by path (never read), so
    // they have no size limit.
    //
    // SOFT guard — above it we keep the clip but store it UNENCRYPTED, skipping
    // the in-memory ciphertext copy that sealing a big blob needs. It still
    // restores (paste-back works) and keeps OS file protection; only app-level
    // encryption is dropped, which is the cost of holding large clips cheaply.
    //
    // HARD guard — above it we keep metadata only (no bytes), so a pathological
    // clip (e.g. a 1 GB paste) can't spike memory or stall the UI.
    private static let softTextBytes = 1 * 1024 * 1024         // ≤1 MB text → encrypt
    private static let maxTextBytes = 100 * 1024 * 1024        // >100 MB text → metadata only
    private static let softImageBytes = 8 * 1024 * 1024        // ≤8 MB PNG → encrypt
    private static let maxImagePixels = 50_000_000             // >50 MP → metadata only (no decode)

    func start() {
        guard !isRunning else { return }
        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer.scheduledTimer(withTimeInterval: pollInterval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // Capture latency is not precision-sensitive; tolerance lets macOS
        // coalesce the wakeup with other timers and cuts idle power.
        timer.tolerance = pollInterval / 2
        self.timer = timer
        RunLoop.main.add(timer, forMode: .common)
        isRunning = true
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        isRunning = false
    }

    /// Drops the `clipboard.changed` event for the next observed change. Called by
    /// the host before every extension-originated write so a handler that writes
    /// the clipboard cannot re-trigger itself forever. History capture is
    /// unaffected — a host write is still a real clip worth remembering.
    func suppressNextChange() { suppressNext = true }

    /// Internal, and takes the pasteboard, so a test can drive one poll against its
    /// own named pasteboard instead of the user's.
    func poll(_ pb: NSPasteboard = .general) {
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        let suppressed = suppressNext
        suppressNext = false
        // Concealed clips return nil here, so the event honours the same privacy
        // guard as history — a password copy never reaches an extension.
        guard let captured = capture(pb) else { return }
        guard !suppressed, shouldEmitChange?() ?? true, let emitChange else { return }
        emitChange(Self.changePayload(kind: captured.kind, text: captured.text))
    }

    /// Classifies the pasteboard and, when `captureHistory` is on, records it in the
    /// history store. Returns the event kind plus the text for `kind == "text"`, or
    /// nil when there is nothing to report (concealed, or empty).
    @discardableResult
    private func capture(_ pb: NSPasteboard) -> (kind: String, text: String?)? {
        // Respect concealed/transient markers (passwords, OTP, etc.).
        if let types = pb.types, !Self.concealedTypes.isDisjoint(with: Set(types)) {
            return nil
        }

        // 1. Files (one or many) — reference by path, don't copy bytes.
        if let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            if captureHistory { for url in urls { ClipboardStore.shared.addFile(url) } }
            return ("file", nil)
        }

        // 2. Image.
        if let images = pb.readObjects(forClasses: [NSImage.self], options: nil) as? [NSImage],
           let image = images.first {
            let (w, h) = Self.pixelSize(of: image)
            // HARD guard on pixel count BEFORE decoding: a giant image's TIFF/PNG
            // would allocate hundreds of MB. Over the limit → metadata only.
            if w > 0, h > 0, w * h > Self.maxImagePixels {
                if captureHistory { ClipboardStore.shared.addOversizeImage(width: w, height: h) }
                return ("image", nil)
            }
            if let png = Self.pngData(from: image) {
                // Keep + restore at any decoded size; encrypt only the small ones.
                if captureHistory {
                    ClipboardStore.shared.addImage(image, pngData: png,
                                                   encrypt: png.count <= Self.softImageBytes)
                }
                return ("image", nil)
            }
        }

        // 3. Text.
        if let string = pb.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let bytes = string.utf8.count
            if captureHistory {
                if bytes > Self.maxTextBytes {
                    // HARD guard → metadata-only marker, never persist the payload.
                    ClipboardStore.shared.addOversizeText(byteCount: bytes,
                                                          preview: String(string.prefix(140)))
                } else {
                    // Keep + restore; encrypt only below the soft threshold.
                    ClipboardStore.shared.addText(string, encrypt: bytes <= Self.softTextBytes)
                }
            }
            return ("text", string)
        }

        return nil
    }

    /// `clipboard.changed` payload. `text` is carried only for `kind == "text"`, and
    /// only up to `maxEventTextBytes`.
    static func changePayload(kind: String, text: String?) -> String {
        var obj: [String: Any] = ["kind": kind]
        if let text { obj["text"] = clipped(text, maxBytes: maxEventTextBytes) }
        guard let data = try? JSONSerialization.data(withJSONObject: obj),
              let s = String(data: data, encoding: .utf8) else { return "{}" }
        return s
    }

    /// Byte-capped prefix that cuts on a Character boundary, so the payload can
    /// never carry a split UTF-8 sequence. The loop is bounded by `maxBytes`, not by
    /// the input length.
    static func clipped(_ s: String, maxBytes: Int) -> String {
        guard s.utf8.count > maxBytes else { return s }
        var out = ""
        out.reserveCapacity(maxBytes)
        var n = 0
        for ch in s {
            let w = ch.utf8.count
            if n + w > maxBytes { break }
            out.append(ch)
            n += w
        }
        return out
    }

    /// Largest pixel dimensions across the image's representations (falls back to
    /// the point size if no bitmap rep reports pixels). Cheap — reads rep
    /// metadata without decoding pixel data.
    private static func pixelSize(of image: NSImage) -> (Int, Int) {
        var w = 0, h = 0
        for rep in image.representations {
            w = max(w, rep.pixelsWide)
            h = max(h, rep.pixelsHigh)
        }
        if w == 0 || h == 0 { return (Int(image.size.width), Int(image.size.height)) }
        return (w, h)
    }

    private static func pngData(from image: NSImage) -> Data? {
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }
}
