import Foundation

/// B2 — a ranked set of alternate inline completions sharing one anchor (the user's
/// before-caret text at request time). Keeping the runners-up (not just the shown
/// best) lets a keystroke that diverges from the displayed ghost swap to a
/// still-valid alternate **without a model round trip**: if what the user just typed
/// is the head of some candidate's prediction, that candidate's remainder is shown
/// instantly. This is the "several continuations, buffer sorted by prefix match"
/// the user asked for; the model breadth (n-best) is generated by the engine, this
/// is the pure selection/re-rank half.
///
/// It is an ACCELERATOR, not the source of truth — the reconcile path still governs
/// correctness. `bestMatching` returns nil (⇒ refire the model) whenever nothing in
/// the buffer cleanly continues the current text.
struct CandidateBuffer: Equatable, Sendable {

    struct Candidate: Equatable, Sendable {
        /// Sanitized completion text (may start with a space for a new word).
        let text: String
        /// Average per-token log-probability; higher = more model-preferred.
        let avgLogprob: Float
    }

    /// The user's before-caret text when these candidates were generated.
    let anchorBefore: String
    /// Candidates, best-first by `avgLogprob`.
    let candidates: [Candidate]

    init(anchorBefore: String, candidates: [Candidate]) {
        self.anchorBefore = anchorBefore
        self.candidates = candidates.sorted { $0.avgLogprob > $1.avgLogprob }
    }

    /// The model-preferred completion (before any divergence).
    var best: String? { candidates.first?.text }

    /// Given the user's CURRENT before-caret text, the best candidate that still
    /// validly continues it — accounting for characters typed since the anchor.
    /// Returns nil when the user diverged from every candidate (⇒ refire the model)
    /// or typed backwards / into unrelated text.
    func bestMatching(currentBefore: String) -> String? {
        guard currentBefore.hasPrefix(anchorBefore) else { return nil }
        let typed = String(currentBefore.dropFirst(anchorBefore.count))
        guard !typed.isEmpty else { return best } // no divergence yet → shown best
        // Candidates are best-first; return the first whose prediction the user is
        // typing into, showing the un-typed remainder.
        for c in candidates where c.text.hasPrefix(typed) {
            let remainder = String(c.text.dropFirst(typed.count))
            if !remainder.isEmpty { return remainder }
        }
        return nil
    }
}
